platform :ios, ‘8.0‘

target "Fairy" do

use_frameworks!

pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'
pod 'IQKeyboardManager' 
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'TYPagerController'
pod 'Charts'
pod 'YCXMenu' ## 菜单选择栏
end
