platform :ios, ‘8.0‘

target "Fairy" do
use_frameworks!


pod 'UMCCommon'
pod 'UMCSecurityPlugins'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMCShare/UI'
# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMCShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
pod 'UMCShare/Social/ReducedSina'



pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'
pod 'IQKeyboardManager' 
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'TYPagerController'
pod 'WMPageController', '~> 2.4.0'  
# pod 'Charts'
pod 'YCXMenu' ## 菜单选择栏


end
